version: '3'

services:
  php:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: pb_php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - net
  mysql:
    image: mysql:latest
    container_name: pb_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - net
  nginx:
    image: nginx:1.23-alpine
    container_name: pb_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - net
networks:
  net:
    driver: bridge