name: Deployment
run-name: Deployment actions
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', 'env.test.local');"
      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests
        run: |
          vendor/bin/phpunit
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Adding known hosts
        run: |
          echo 'Running ssh keyscan'
          ssh-keyscan -H -p ${{ secrets.SSH_HOST_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Clearing
        run: |
          ssh server@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_HOST_PORT }} "cd Documents\localhost && del * /S /Q"
      - name: Copy project files to host
        run: |
          echo 'Trying to copy files via scp'
          scp -P ${{ secrets.SSH_HOST_PORT }} -r ./* server@${{ secrets.SSH_HOST }}:'C:\Users\server\Documents\localhost'
          scp -P ${{ secrets.SSH_HOST_PORT }} -r ./.env server@${{ secrets.SSH_HOST }}:'C:\Users\server\Documents\localhost'
      - name: Build and start application in docker container
        run: |
          echo 'Trying to start application. Make sure docker is running on host'
          ssh server@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_HOST_PORT }} "cd Documents\localhost && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist || docker rm $(docker ps -aq) && docker compose up ---pull never -build -d"
